# 签到记录
query CheckInsQuery($days: Int) {
    checkIns(days: $days) {
        today_checked
        keep_checkin_days
        checks {
            year
            date
            created_at
            checked
            gold_reward
            reward_rate
        }
    }
}

# 签到
mutation CreateCheckInMutation {
    createCheckIn {
        id
        gold_reward
        keep_checkin_days
    }
}
