#签到额外奖励接口
# SIGNIN_VIDEO_REWARD 签到奖励
# DOUBLE_SIGNIN_REWARD 双倍奖励
# WATCH_REWARD_VIDEO 激励视频奖励
mutation UserRewardMutation($reason: RewardEnum) {
    reward(reason: $reason) {
        gold
        ticket
    }
}

# 任务领取奖励
mutation rewardTaskMutation($id: ID!) {
    rewardTask(id: $id) {
        id
        reward_info {
            gold
            ticket
            gold_high
            ticket_high
        }
    }
}

#新用户奖励接口
# "rewardType": "VIDEO"
mutation newUserRewordMutation($rewardType: RewardType!) {
    newUserReword(type: $rewardType)
}
